install: true

sudo: false

language: python

python:
  - 3.4

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

before_install:
  - "pip install -U pip"

script:
  - pytest
